MAP_XSIZE = 20
MAP_YSIZE = 57

CHR_EMPTY =  ' '
CHR_STONE =  'O' #| COLOR_PAIR(COLOR_WHITE)  | A_NORMAL
CHR_WALL  =  ':' #| COLOR_PAIR(COLOR_CYAN)   | A_NORMAL
CHR_PLAYER_1  = 'S'# | COLOR_PAIR(COLOR_WHITE)  | A_BOLD
CHR_PLAYER_2 = 'A'
CHR_PLAYER_3 = 'B'
CHR_PLAYER_4 = 'C'
CHR_PLAYER_5 = 'D'
CHR_BOMB    = '@'# | COLOR_PAIR(COLOR_BLUE)   | A_BOLD
CHR_EXPLOSION = '*'

MAP_EMPTY = 0
MAP_STONE = 1
MAP_PLAYER_1 = 2
MAP_PLAYER_2 = 3
MAP_PLAYER_3 = 4
MAP_PLAYER_4 = 5
MAP_PLAYER_5 = 6
MAP_WALL = 7
MAP_BOMB = 8
MAP_EXPLOSION = 9

g_map = []
g_bombs = []
g_users = {}
